--- !ruby/object:Railsui::Configuration
application_name: bms Ops
support_email: support@bmserp.com
theme: retriever
pages:
- about
- pricing
- overview
- apps
- app
- app_activity
- app_domains
- app_access
- app_settings
- servers
- domains
- databases
- deploys
- users
- analytics
- settings
- empty
- notifications
- support
- changelog
- changelog_detail
- privacy_policy
- terms
- contact
- settings_billing
- settings_notifications
- settings_team
- settings_integrations
build_mode: nobuild
body_classes: h-full antialiased text-gray-900 leading-normal selection:bg-primary-100
  selection:text-primary-700 dark:bg-gray-900 bg-white dark:text-gray-50 dark:selection:bg-primary-500/40
  dark:selection:text-gray-100
